#!/bin/bash

set -e

if [ $# -ne 1 ]
then
    echo "usage: $(basename $0) <path-to-git-repo>"
    exit 2
fi

function get_property
{
        grep "^$2=" "$1" | cut -d'=' -f2
}

if [ ! -f $1/settings.gradle ]
then
    echo "shit"
    exit 2
fi

projectName=$(get_property $1/settings.gradle rootProject.name | sed 's/\"//g' | sed "s/\'//g")
git bundle create $projectName.bundle --all
echo ""
echo "Bundled project $projectName to $projectName.bundle"
echo "Done"

