#!/bin/bash

set -e

show_usage() {
cat << EOF
Usage: ${0##*/} <IL no.>/<hostname>

Grab the Dispatch jars and config from an IL, to create a Palantir SDK in IntelliJ. Note:
    * Assumes you have installed 'insta'.
    * Assumes you have installed 'ssh-copy-id' (brew install ssh-copy-id)

    <IL no.>    insta host ID for the source IL (run 'insta list' to determine the correct ID).
    <hostname>  hostname of the source IL

Examples:
    '${0##*/} 0'

See Also:
    palantir-intellij-plugin:   https://github.palantir.build/gotham/pg-intellij-plugin
    insta:                      https://github.palantir.build/gotham/insta

EOF
}

# validate argument
case $1 in
    [0-9]*)
        insta=1
        il_host=$(insta hostname $1)
        ;;
    -h | --help)
        show_usage
        exit 0
        ;;
    *)
        insta=0
        il_host=$1
esac
set -u

if [ $insta -eq 1 ]; then
    il_pass=$( insta p $il_num )
    echo "Your palantir IL Password is: $il_pass"
fi
lib_base=~/palantir-lib
copy_cmd="rsync -crv --delete-after"

# setup passwordless-ssh to avoid multiple password entries
ssh-copy-id palantir@$il_host

# locate dispatch home
il_dispatch_home=$( ssh palantir@$il_host find -L /opt/palantir/services -maxdepth 1 -name "*dispatch*"  )
# determine version of Gotham on IL by examining patch jar
#if $( ssh palantir@$il_host test -f $il_dispatch_home/service/lib/client-patch/patch.jar palantir-patch_info.properties  ); then
#    ssh palantir@$il_host jar xf $il_dispatch_home/service/lib/client-patch/patch.jar palantir-patch_info.properties
#    il_version=$( ssh palantir@$il_host cat palantir-patch_info.properties | grep \"Base\": | sed 's/.*\(3\.[1-9][0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g' )
#else
    il_version=$( ssh palantir@$il_host find $il_dispatch_home/service/lib/client/pg-client-resources*jar | sed 's/.*\(3\.[1-9][0-9]*.*\).jar/\1/g' )
#fi

mkdir -p $lib_base/$il_version/service/lib
mkdir -p $lib_base/$il_version/var/conf

# rsync relevant libs and config
$copy_cmd palantir@$il_host:$il_dispatch_home/service/lib/client $lib_base/$il_version/service/lib
$copy_cmd palantir@$il_host:$il_dispatch_home/service/lib/client-patch $lib_base/$il_version/service/lib
$copy_cmd palantir@$il_host:$il_dispatch_home/var/conf/security $lib_base/$il_version/var/conf
$copy_cmd palantir@$il_host:$il_dispatch_home/var/conf/webstart $lib_base/$il_version/var/conf

