#!/bin/sh
 
function abort {
  echo "$1"
  exit 1
}
 
set -e
 
read -p "Are you sure you want to uninstall homebrew ("yes")? " -r
# move to a new line
echo # move to a new line

if [[ $REPLY =~ ^yes$ ]]
then
    /usr/bin/which -s git || abort "brew install git first!"
    test -d /usr/local/.git || abort "brew update first!"
 
    cd `brew --prefix`
    git checkout master
    git ls-files -z | pbcopy
    rm -rf Cellar
    bin/brew prune
    pbpaste | xargs -0 rm
    rm -r Library/Homebrew Library/Aliases Library/Formula Library/Contributions 
    test -d Library/LinkedKegs && rm -r Library/LinkedKegs
    rmdir -p bin Library share/man/man1 2> /dev/null
    rm -rf .git
    rm -rf ~/Library/Caches/Homebrew
    rm -rf ~/Library/Logs/Homebrew
    rm -rf /Library/Caches/Homebrew
fi

