#!/bin/bash

set -e

dispatch_path="/opt/palantir/services/dispatch-0"
admin_url="-u p://admin:palantir@localhost:3280"
coal_version="3.13.4.3.673555.86_1.12.1"
coal_url="https://artifactory.yojoe.local/artifactory/ivy-libs-snapshot/com.palantir/coal-audit-loggers/pg${coal_version}/coal-audit-loggers-pg${coal_version}.par"

function get_coal_par {
    if [ "$1" ]
    then
        echo "$1"
    else
        wget -O coal.par --no-check-certificate $coal_url
        echo "coal.par"
    fi
}

# validate args
if [ $# -lt 1 -o $# -gt 2 ]
then
   echo `basename $0` "<instance id> [optional: coal par]"
   exit 1
fi

ipasswordless-ssh $1


# process args
ssh_host=$(insta hostname $1)
ssh_user=palantir

coal_par=$(get_coal_par $2)
echo "Installing $coal_par to $ssh_host..."
iscp $coal_par $1

ssh $ssh_user@$ssh_host "${dispatch_path}/bin/unix/systemPropertyUtil.sh -s ENABLE_CLIENT_AUDIT_LOGGING true ${admin_url}"
ssh $ssh_user@$ssh_host "sed -i 's/^log4j.appender.xmlAuditLogAppend.selectedAuditTags=SECURITY_RELATED$/log4j.appender.xmlAuditLogAppend.selectedAuditTags=SECURITY_RELATED,CLIENT_RELATED/g' ${dispatch_path}/dispatch.log.properties"
ssh $ssh_user@$ssh_host "sed -i 's/^log4j.appender.dbAuditLogAppend.selectedAuditTags=SECURITY_RELATED$/log4j.appender.dbAuditLogAppend.selectedAuditTags=SECURITY_RELATED,CLIENT_RELATED/g' ${dispatch_path}/dispatch.log.properties"
ssh $ssh_user@$ssh_host "${dispatch_path}/bin/unix/managePlugins.sh -i -g -f /home/palantir/coal.par ${admin_url}"

