#!/bin/bash

set -e

# validate args
if [ $# -ne 2 ]
then
   echo `basename $0` "<instance id> <almanac url>"
   exit 1
fi

ipasswordless-ssh $1

# process args
ssh_host=$(insta hostname $1)
ssh_user=palantir

ssh -t $ssh_user@$ssh_host "rm -f *.tgz && aws s3 cp $2 ."
ssh -t $ssh_user@$ssh_host "install_module.sh -e production -p ~/\$(find . -maxdepth 1 -name '*.tgz')"

