#!/bin/bash

# description: initiates password-less ssh via RSA for the current user, on the current host, to a specified user on a remote machine.
#
# author: clormor (https://github.com/clormor)
#
# usage: passwordless-ssh <remote user name>@<remote host>
#

set -e

# validate args
if [ $# -ne 1 ]
then
   echo `basename $0` "<instance id>"
   exit 1
fi

# process args
ssh_host=$(insta hostname $1)
ssh_user=palantir

# generate RSA key if required
if [ ! -f ~/.ssh/id_rsa.pub ]
then
   echo "generating RSA keys for this user..."
   ssh-keygen -t rsa
fi

echo "When it asks for a password, use this..."
echo $(insta password $1)

# copy ssh id to remote host
ssh-copy-id $ssh_user@$ssh_host

#log in
ssh $ssh_user@$ssh_host
