#!/bin/bash

set -e

dispatch_path="/opt/palantir/services/dispatch-0"
admin_url="-u p://admin:palantir@localhost:3280"

# validate args
if [ $# -ne 2 ]
then
   echo `basename $0` "<instance id> {start|stop|restart}"
   exit 1
fi

ipasswordless-ssh $1

# process args
ssh_host=$(insta hostname $1)
ssh_user=palantir

ssh $ssh_user@$ssh_host "${dispatch_path}/bin/unix/ptdispatch.sh $2"

