#!/bin/bash

set -e

# validate args
if [ $# -ne 2 ]
then
   echo `basename $0` "<file> <instance id>"
   exit 1
fi

ipasswordless-ssh $2

# process args
ssh_host=$(insta hostname $2)
ssh_user=palantir

# copy the file
scp $1 $ssh_user@$ssh_host:~
