#!/bin/bash

set -e

default_version=1.1.1

# validate args
if [ $# -lt 1 -o $# -gt 2 ]
then
    echo `basename $0` "<instance id> [optional: skylab version (default: $default_version)]"
    exit 1
fi

if [ "$2" ]
then
    module_version=$2
else
    module_version=${default_version}
fi

# process args
ssh_host=$(insta hostname $1)
ssh_user=palantir

almanac_url="s3://il-pdreleases-use/skylab-module/${module_version}/0/skylab-module-${module_version}.tgz"

ihouston-install_module $1 $almanac_url

axiom=$(echo "$(insta hostname 0.0),$(insta hostname 0.1),$(insta hostname 0.2)")
echo "axiom is $axiom"
ssh -t $ssh_user@$ssh_host "forearm dump > houston-config.yml"
ssh -t $ssh_user@$ssh_host "sed -i 's/^hosts:$/hostgroups:\n  skylab:\n    classes:\n    - skylab\n    parameters:\n      axiom_hosts: ${axiom}\nhosts:/g' houston-config.yml"
ssh -t $ssh_user@$ssh_host "sed -i 's/^    environment: production$/    environment: production\n    hostgroup: skylab/g' houston-config.yml"
ssh -t $ssh_user@$ssh_host "forearm push houston-config.yml"

#if [ "$3" -a "$4" ]
#then
#    ssh -t $ssh_user@$ssh_host "sed -i 's/^ALMANAC_ACCESS_ID=$/ALMANAC_ACCESS_ID=$3/g' /opt/palantir/houston/data/etc/skylab.conf"
#    ssh -t $ssh_user@$ssh_host "sed -i 's/^ALMANAC_SECRET_KEY=$/ALMANAC_SECRET_KEY=$4/g' /opt/palantir/houston/data/etc/skylab.conf"
#fi

ssh -t $ssh_user@$ssh_host "\$HOUSTON_DATA/config/files/install_skylab.sh -hg skylab -fp palantir -y"

echo "Type in what you want the multipass admin password to be (suggestion: palantir)"
ssh -t $ssh_user@$ssh_host "deployctl service secret-set multipass --stack management --secret-name adminPassword"

insta gemini $1

