#!/bin/bash

# description: initiates password-less ssh via RSA for the current user, on the current host, to a specified user on a remote machine.
#
# author: clormor (https://github.com/clormor)
#
# usage: passwordless-ssh <remote user name>@<remote host>
#

set -e

# process args
r_user_host=$1

# validate args
if [ $# -ne 1 ]
then
   echo `basename $0` "<remote user>@<remote host>"
   exit 1
fi

if [[ "$1" == *"@"* ]]; then
    ssh_user=$(echo $1 | cut -f 1 -d '@')
    ssh_host=$(echo $1 | cut -f 2 -d '@')
else
    ssh_user=$USER
    ssh_host=$1
fi

# generate RSA key if required
if [ ! -f ~/.ssh/id_rsa.pub ]
then
   echo "generating RSA keys for this user..."
   ssh-keygen -t rsa
fi

# copy ssh id to remote host
ssh-copy-id $ssh_user@$ssh_host

