#!/bin/bash


GRADLE_HOME=~/.gradle
BACKUP_TIMESTAMP=$(date +"%s")
SKIP_BACKUP=0

function find_backups {
    echo "Found the following potential timestamps..."
    find ~/.gradle -maxdepth 1 -type d -name "*backup-*" -exec basename {} \; | cut -f 3 -d '-' | sort | uniq
    exit 0
}

function backup_dir {
    if [ ${SKIP_BACKUP} -eq 0 ]
    then
        if [ -d $1 ]
        then
            mv -v $1 $1-backup-${BACKUP_TIMESTAMP}
        else
            echo "No directory found at $1: Assuming a fresh Gradle home and skipping..."
            SKIP_BACKUP=1
        fi
    fi
}

function restore_dir {
    if [ -d $1-backup-${RESTORE_TIMESTAMP} ]
    then
        mv -v $1-backup-${RESTORE_TIMESTAMP} $1
    else
        echo "No directory found at $1-backup-${RESTORE_TIMESTAMP}. Exiting"
        exit 1
    fi
}

if [ $# -ne 1 ]
then
    echo "Usage: $(basename $0) <timestamp of backup directories to restore>"
    find_backups
fi

RESTORE_TIMESTAMP=$1

if [ -d ${GRADLE_HOME} ]
then
    echo "First, backing up existing ${GRADLE_HOME} using timestamp ${BACKUP_TIMESTAMP}..."
    backup_dir ${GRADLE_HOME}/caches
    backup_dir ${GRADLE_HOME}/daemon
    backup_dir ${GRADLE_HOME}/native
    backup_dir ${GRADLE_HOME}/wrapper
    echo "Restoring ${GRADLE_HOME} using timestamp $1..."
    restore_dir ${GRADLE_HOME}/caches
    restore_dir ${GRADLE_HOME}/daemon
    restore_dir ${GRADLE_HOME}/native
    restore_dir ${GRADLE_HOME}/wrapper
else
    echo "No gradle home found at ${GRADLE_HOME}"
    exit 1
fi

