#!/bin/bash

function printDate {
    DATE_FORMAT="$1%t%a %b %e %R (GMT %z)"
    echo "  $(TZ=$2 date "+$DATE_FORMAT")"
}

printDate London Europe/London
printDate California America/Los_Angeles
printDate Washington America/New_York
printDate Canberra Australia/Canberra
printDate Wellington Pacific/Auckland

