#!/bin/bash

GRADLE_HOME=~/.gradle
BACKUP_TIMESTAMP=$(date +"%s")
RESTORE_TIMESTAMP=$1
SKIP_BACKUP=0

function backup_dir {
    if [ ${SKIP_BACKUP} -eq 0 ]
    then
        if [ -d $1 ]
        then
            mv -v $1 $1-backup-${BACKUP_TIMESTAMP}
        else
            echo "No directory found at $1: Assuming a fresh Gradle home and skipping..."
            SKIP_BACKUP=1
        fi
    fi
}

if [ -d ${GRADLE_HOME} ]
then
#    echo "First, backing up existing ${GRADLE_HOME} using timestamp ${BACKUP_TIMESTAMP}..."
#    backup_dir ${GRADLE_HOME}/caches
#    backup_dir ${GRADLE_HOME}/daemon
#    backup_dir ${GRADLE_HOME}/native
#    backup_dir ${GRADLE_HOME}/wrapper
    echo "Cleaning ${GRADLE_HOME}..."
    echo "NOTE: ${GRADLE_HOME}/gradle.properties and any backups will be preserved"
    rm -vrf ${GRADLE_HOME}/caches
    rm -vrf ${GRADLE_HOME}/daemon
    rm -vrf ${GRADLE_HOME}/native
    rm -vrf ${GRADLE_HOME}/wrapper
else
    echo "No gradle home found at ${GRADLE_HOME}"
    exit 1
fi

